http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  productos_req:
    host: localhost
    methods: 'GET,POST,PUT,DELETE'
    paths: ['/products/*']
  usuarios_req:
    host: localhost
    methods: 'GET,POST,PUT,DELETE'
    paths: ['/auth/*']
serviceEndpoints:
  productos_resp:
    url: 'https://productos-api-heroku.herokuapp.com'
  usuarios_resp:
    url: 'https://usuarios-api-heroku.herokuapp.com'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  productos_pipeline:
    apiEndpoints:
      - productos_req
    policies:
      - proxy:
          - action:
              serviceEndpoint: productos_resp
              changeOrigin: true
  usuarios_pipeline:
    apiEndpoints:
      - usuarios_req
    policies:
      - proxy:
          - action:
              serviceEndpoint: usuarios_resp
              changeOrigin: true
